### ISSUE TITLE
save mode

### ISSUE THREAD

**Issue by qwertyuiop194** [creafz/pytorch-cnn-finetune#17]
When saving the resnext101_64x4d model, the following error occurred. There is no such problem in saving other models. What is the reason?

Traceback (most recent call last):
  File "resnext101_64x4d_CellData.py", line 251, in <module>
    main()
  File "resnext101_64x4d_CellData.py", line 243, in main
    max_acc = test(model, test_loader,max_acc,epoch_test)
  File "resnext101_64x4d_CellData.py", line 130, in test
    torch.save(model,'./models/%s.pth'%args.model_name)
  File "/home/zlw/.local/lib/python3.5/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zlw/.local/lib/python3.5/site-packages/torch/serialization.py", line 185, in _with_file_like
    return body(f)
  File "/home/zlw/.local/lib/python3.5/site-packages/torch/serialization.py", line 260, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zlw/.local/lib/python3.5/site-packages/torch/serialization.py", line 332, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7ff02de7b0d0>: attribute lookup <lambda> on pretrainedmodels.models.resnext_features.resnext101_64x4d_features failed

**Comment by creafz** [comment]
Under the hood, cnn_finetune uses the [pretrainedmodels](https://github.com/Cadene/pretrained-models.pytorch) package to initialize the resnext model. The problem is that the resnext model contains lambda functions, and torch.save can't serialize them.

There are two possible workarounds for this issue:

1. You can save only the state dict instead of the whole model: `torch.save(model.state_dict() ,'./models/%s.pth'%args.model_name)`
2. You can install the latest version of pretrainedmodels from GitHub. This version doesn't use lambda functions for resnext models, so you should be able to save the whole model:
```
pip uninstall pretrainedmodels
pip install git+https://github.com/Cadene/pretrained-models.pytorch.git
```
